import test from 'node:test';
import assert from 'node:assert/strict';
import { existsSync, mkdirSync, mkdtempSync, readFileSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import Database from 'better-sqlite3';
import { ALGORITHM_VERSION } from '../src/config.mjs';
import { addQuery, getMeta, openDatabase, setMeta } from '../src/db.mjs';
import { reclassifyRun } from '../src/reclassify-run.mjs';
import { findResumableRun } from '../src/run-version.mjs';

test('offline reclassification creates a consistent WAL-aware backup without API clients', async () => {
  const runDir = mkdtempSync(join(tmpdir(), 'wordmap-reclassify-'));
  mkdirSync(join(runDir, 'raw'));
  writeFileSync(join(runDir, 'input.txt'), '@entity DLE130G\nтопливный бак БПЛА\n');
  const databaseFile = join(runDir, 'research.sqlite');
  let db = openDatabase(databaseFile);
  const parent = addQuery(db, 'DLE130G engine', { manualSeed: true, status: 'done' });
  const relevant = addQuery(db, 'DLE130G fuel system', { status: 'stored', relevanceClass: 'noise' });
  const noise = addQuery(db, 'топливный бак ВАЗ', { status: 'stored', relevanceClass: 'core', recursiveEligible: true, deepEligible: true });
  db.prepare('INSERT INTO relations VALUES(?,?,?,?,?)').run(parent.id, relevant.id, 'DIRECT', 20, new Date().toISOString());
  db.prepare('INSERT INTO relations VALUES(?,?,?,?,?)').run(parent.id, noise.id, 'ASSOCIATION', 10, new Date().toISOString());
  db.prepare('INSERT INTO api_calls(api,method,success,started_at) VALUES(?,?,?,?)').run('wordstat', 'getTopRequests', 1, new Date().toISOString());
  const before = Object.fromEntries(['queries', 'relations', 'api_calls', 'wordstat_top', 'dynamics', 'regions', 'serp'].map((table) => [table, db.prepare(`SELECT COUNT(*) count FROM ${table}`).get().count]));
  assert.ok(existsSync(`${databaseFile}-wal`));
  await reclassifyRun(runDir);
  assert.ok(existsSync(join(runDir, 'research.before-reclassify.sqlite')));
  const backup = new Database(join(runDir, 'research.before-reclassify.sqlite'), { readonly: true });
  assert.equal(backup.prepare("SELECT COUNT(*) count FROM queries WHERE query='DLE130G fuel system'").get().count, 1);
  assert.equal(backup.prepare('SELECT COUNT(*) count FROM relations').get().count, 2);
  assert.equal(backup.prepare('SELECT COUNT(*) count FROM api_calls').get().count, 1);
  backup.close();
  db.close();
  const originalBackup = readFileSync(join(runDir, 'research.before-reclassify.sqlite'));
  await reclassifyRun(runDir);
  assert.deepEqual(readFileSync(join(runDir, 'research.before-reclassify.sqlite')), originalBackup);
  assert.ok(existsSync(join(runDir, 'queries.csv')));
  assert.match(readFileSync(join(runDir, 'report.html'), 'utf8'), /ADJACENT/u);
  db = openDatabase(databaseFile);
  const after = Object.fromEntries(Object.keys(before).map((table) => [table, db.prepare(`SELECT COUNT(*) count FROM ${table}`).get().count]));
  assert.deepEqual(after, before);
  assert.equal(getMeta(db, 'algorithm_version'), undefined);
  assert.equal(getMeta(db, 'reclassification_algorithm_version'), String(ALGORITHM_VERSION));
  assert.equal(getMeta(db, 'resume_disabled'), '1');
  assert.deepEqual(db.prepare('SELECT relevance_class,recursive_eligible,deep_eligible,status FROM queries WHERE id=?').get(relevant.id), { relevance_class: 'adjacent', recursive_eligible: 1, deep_eligible: 1, status: 'stored' });
  assert.deepEqual(db.prepare('SELECT relevance_class,recursive_eligible,deep_eligible,status FROM queries WHERE id=?').get(noise.id), { relevance_class: 'noise', recursive_eligible: 0, deep_eligible: 0, status: 'stored' });
  db.close();
});

test('reclassified paused legacy run remains analysis-only and cannot resume', async () => {
  const resultsRoot = mkdtempSync(join(tmpdir(), 'wordmap-analysis-only-'));
  const runDir = join(resultsRoot, 'legacy-run');
  mkdirSync(join(runDir, 'raw'), { recursive: true });
  writeFileSync(join(runDir, 'input.txt'), 'топливный бак БПЛА\n');
  const db = openDatabase(join(runDir, 'research.sqlite'));
  setMeta(db, 'input_hash', 'legacy-hash');
  setMeta(db, 'status', 'paused');
  setMeta(db, 'algorithm_version', 3);
  db.close();
  await reclassifyRun(runDir);
  const checked = openDatabase(join(runDir, 'research.sqlite'));
  assert.equal(getMeta(checked, 'algorithm_version'), '3');
  assert.equal(getMeta(checked, 'reclassification_algorithm_version'), String(ALGORITHM_VERSION));
  assert.equal(getMeta(checked, 'resume_disabled'), '1');
  checked.close();
  assert.equal(findResumableRun(resultsRoot, 'legacy-hash'), undefined);
});
