import { writeFileSync } from 'node:fs';
export function csvEscape(value) { const text=value==null?'':String(value); return /[;"\r\n]/u.test(text)?`"${text.replaceAll('"','""')}"`:text; }
const csv=(headers,rows)=>'\uFEFF'+[headers,...rows.map(row=>headers.map(h=>row[h]))].map(row=>row.map(csvEscape).join(';')).join('\r\n')+'\r\n';
const escapeHtml=(v)=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
export function generateReport(db,runDir,{intermediate=false}={}){
  const queries=db.prepare('SELECT q.*,w.total_count FROM queries q LEFT JOIN wordstat_top w ON w.query_id=q.id ORDER BY q.score DESC,q.id').all();
  writeFileSync(`${runDir}/queries.csv`,csv(['id','query','normalized','depth','score','manual_seed','brand_seed','status','total_count'],queries));
  if(intermediate)return;
  const specs=[['clusters','SELECT c.id,c.name,q.query,q.score FROM clusters c JOIN cluster_queries cq ON cq.cluster_id=c.id JOIN queries q ON q.id=cq.query_id'],['serp','SELECT q.query,s.position,s.url,s.normalized_url,s.domain,s.title,s.snippet FROM serp s JOIN queries q ON q.id=s.query_id'],['dynamics','SELECT q.query,d.date,d.count,d.share FROM dynamics d JOIN queries q ON q.id=d.query_id'],['regions','SELECT q.query,r.region_id,r.region_name,r.count,r.share,r.affinity_index FROM regions r JOIN queries q ON q.id=r.query_id']];
  const data={};for(const [name,sql] of specs){const rows=db.prepare(sql).all();data[name]=rows;writeFileSync(`${runDir}/${name}.csv`,csv(rows.length?Object.keys(rows[0]):[],rows));}
  const section=(title,rows,columns=['query','score','total_count'])=>`<section><h2>${title}</h2><table><thead><tr>${columns.map(x=>`<th>${escapeHtml(x)}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${columns.map(x=>`<td>${escapeHtml(r[x])}</td>`).join('')}</tr>`).join('')}</tbody></table></section>`;
  const html=`<!doctype html><html lang="ru"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>Wordmap — отчёт</title><style>body{font:15px system-ui;margin:2rem;color:#172033;background:#f5f7fb}h1,h2{color:#183b70}section{background:white;padding:1rem;margin:1rem 0;border-radius:10px;box-shadow:0 2px 8px #0001;overflow:auto}.note{border-left:5px solid #d98300}table{border-collapse:collapse;width:100%}th,td{padding:.45rem;border-bottom:1px solid #ddd;text-align:left}th{background:#eef3fa}</style><body><h1>Исследование поисковых запросов</h1><section><b>Всего запросов:</b> ${queries.length}; <b>кластеров:</b> ${new Set(data.clusters.map(x=>x.id)).size}; <b>SERP-строк:</b> ${data.serp.length}</section><section class="note">Частотности Wordstat пересекаются и не являются количеством уникальных пользователей. Суммировать их напрямую нельзя.</section>${section('Manual seeds',queries.filter(x=>x.manual_seed))}${section('HIGH priority',queries.filter(x=>x.score>=6))}${section('Commercial',queries.filter(x=>/(купить|цена|заказ|производ|поставщик|продажа)/iu.test(x.query)))}${section('Брендовые',queries.filter(x=>x.brand_seed))}${section('Haoye',queries.filter(x=>/haoye/iu.test(x.query)))}${section('Кластеры',data.clusters,['id','name','query','score'])}${section('SERP domains',data.serp,['query','position','domain','url'])}${section('Dynamics',data.dynamics,['query','date','count','share'])}${section('Regions',data.regions,['query','region_name','count','share','affinity_index'])}${section('Noise',queries.filter(x=>x.score<3))}</body></html>`;writeFileSync(`${runDir}/report.html`,html);
}
