import { writeFileSync } from 'node:fs';
import { addQuery, getMeta, setMeta } from './db.mjs';
import { normalizeQuery, normalizeUrl, scoreQuery } from './scoring.mjs';
import { completedPeriod, PERIOD_MONTHLY } from './vendor/yandex/wordstat-dates.mjs';
export const MAX_DEPTH = 2;
export const BRAND_TERMS = ['', 'fuel tank','fuel fitting','fuel clunk','fuel filter','fuel valve','fuel tubing','топливный бак','штуцер','топливный штуцер','топливный фильтр','топливный клапан','топливная трубка'];
export function parseInput(text) { const seeds=[], brands=[]; for (const raw of text.split(/\r?\n/u)) { const line=raw.trim(); if (!line || line.startsWith('#')) continue; if (/^@brand\s+/iu.test(line)) brands.push(line.replace(/^@brand\s+/iu,'').trim()); else seeds.push(line); } return { seeds, brands }; }
export function expandBrands(brands) { return brands.flatMap((brand) => BRAND_TERMS.map((term) => !term ? brand : /[а-яё]/iu.test(term) ? `${term} ${brand}` : `${brand} ${term}`)); }
export function selectRecursiveChildren(children) { const sort=(a,b)=>b.score-a.score || b.count-a.count; return [...children.filter(x=>x.type==='DIRECT'&&x.score>=3).sort(sort).slice(0,100), ...children.filter(x=>x.type==='ASSOCIATION'&&x.score>=5).sort(sort).slice(0,20)]; }
export function intersectionSize(a,b) { let n=0; for (const value of a) if (b.has(value)) n++; return n; }
export function connectedComponents(items, edges) { const graph=new Map(items.map(x=>[x,new Set()])); for(const [a,b] of edges){graph.get(a)?.add(b);graph.get(b)?.add(a);} const seen=new Set(), out=[]; for(const item of items){if(seen.has(item))continue;const stack=[item],part=[];seen.add(item);while(stack.length){const x=stack.pop();part.push(x);for(const y of graph.get(x)){if(!seen.has(y)){seen.add(y);stack.push(y);}}}out.push(part);}return out; }
export async function runResearch({ db, client, runDir, brands, generateReport }) {
  if (!getMeta(db,'regions_tree')) setMeta(db,'regions_tree',JSON.stringify(await client.getRegionsTree()));
  for (;;) { const parent=db.prepare("SELECT * FROM queries WHERE status='queued' AND depth<=? ORDER BY manual_seed DESC,score DESC,depth ASC,id ASC LIMIT 1").get(MAX_DEPTH); if(!parent)break; db.prepare("UPDATE queries SET status='processing' WHERE id=?").run(parent.id);
    try { const raw=await client.getTopRequests(parent.query,parent.id); db.prepare('INSERT OR REPLACE INTO wordstat_top VALUES(?,?,?,?)').run(parent.id,raw.totalCount??raw.total_count??0,JSON.stringify(raw),new Date().toISOString()); const all=[...(raw.results??[]).map(x=>({...x,type:'DIRECT'})),...(raw.associations??[]).map(x=>({...x,type:'ASSOCIATION'}))]; const candidates=[]; for(const x of all){const phrase=x.phrase??x.query??x.text;if(!phrase)continue;const score=scoreQuery(phrase,{brands});const child=addQuery(db,phrase,{depth:parent.depth+1,score,status:'stored',rootSeed:parent.root_seed});db.prepare('INSERT OR REPLACE INTO relations VALUES(?,?,?,?,?)').run(parent.id,child.id,x.type,x.count??0,new Date().toISOString());candidates.push({id:child.id,type:x.type,score,count:x.count??0});} for(const child of selectRecursiveChildren(candidates)) if(parent.depth+1<=MAX_DEPTH) db.prepare("UPDATE queries SET status='queued' WHERE id=? AND status='stored'").run(child.id); db.prepare("UPDATE queries SET status='done' WHERE id=?").run(parent.id); await generateReport?.(false);
    } catch(error){db.prepare("UPDATE queries SET status='queued' WHERE id=?").run(parent.id); if(/запрещен/iu.test(error.message))throw error; console.error(`Запрос «${parent.query}» отложен: ${error.message}`); break;}}
  const dates=completedPeriod(PERIOD_MONTHLY,24); const deep=db.prepare('SELECT * FROM queries WHERE manual_seed=1 OR score>=6').all();
  for(const q of deep){try{if(!db.prepare('SELECT 1 FROM dynamics WHERE query_id=?').get(q.id)){const data=await client.getDynamics(q.query,dates,q.id);for(const x of data.dynamics??data.results??[])db.prepare('INSERT OR REPLACE INTO dynamics VALUES(?,?,?,?)').run(q.id,x.date,x.count??0,x.share??null);}if(!db.prepare('SELECT 1 FROM regions WHERE query_id=?').get(q.id)){const data=await client.getRegionsDistribution(q.query,q.id);for(const x of data.regions??data.results??[])db.prepare('INSERT OR REPLACE INTO regions VALUES(?,?,?,?,?,?)').run(q.id,String(x.regionId??x.id),x.regionName??x.name,x.count??0,x.share??null,x.affinityIndex??null);}if(!db.prepare('SELECT 1 FROM serp WHERE query_id=?').get(q.id)){const {results,rawXml}=await client.search(q.query);writeFileSync(`${runDir}/raw/serp_${q.id}.xml`,rawXml);for(const x of results)db.prepare('INSERT OR REPLACE INTO serp VALUES(?,?,?,?,?,?,?,?)').run(q.id,x.position,x.url,normalizeUrl(x.url),x.domain,x.title,x.snippet,new Date().toISOString());}}catch(error){if(/запрещен/iu.test(error.message))throw error;console.error(`Глубокий анализ «${q.query}» отложен: ${error.message}`);}}
}
export function clusterSerp(db){db.exec('DELETE FROM cluster_queries; DELETE FROM clusters');const rows=db.prepare('SELECT q.id,q.query,q.score,COALESCE(w.total_count,0) total_count,s.normalized_url FROM queries q JOIN serp s ON s.query_id=q.id LEFT JOIN wordstat_top w ON w.query_id=q.id').all(),map=new Map();for(const r of rows){if(!map.has(r.id))map.set(r.id,{...r,urls:new Set()});map.get(r.id).urls.add(r.normalized_url);}const ids=[...map.keys()],edges=[];for(let i=0;i<ids.length;i++)for(let j=i+1;j<ids.length;j++)if(intersectionSize(map.get(ids[i]).urls,map.get(ids[j]).urls)>=3)edges.push([ids[i],ids[j]]);for(const part of connectedComponents(ids,edges)){const best=part.map(id=>map.get(id)).sort((a,b)=>b.score-a.score||b.total_count-a.total_count)[0];const info=db.prepare('INSERT INTO clusters(name) VALUES(?)').run(best.query);for(const id of part)db.prepare('INSERT INTO cluster_queries VALUES(?,?)').run(info.lastInsertRowid,id);}return connectedComponents(ids,edges);}
